// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SchemaField describes one editable setting for the settings UI. The JSON
 * shape is the /api/v1/settings/schema contract, shared by the webapp and
 * the desktop bindings.
 */
export interface SchemaField {
    "key": string;
    "label": string;
    "help": string;
    "obtain"?: string;
    "tvVisible": boolean;
    "sensitive": boolean;
    "restartRequired": boolean;
    "readOnly": boolean;
}

/**
 * SettingsView is the GET /api/v1/settings body: the settings with the four
 * secrets blanked, one Configured flag per secret, and the settings file
 * path. The HTTP handler and the desktop bindings both serve this shape.
 */
export interface SettingsView {
    "instanceName": string;
    "listenAddress": string;
    "trustedCidrs": string[] | null;
    "databasePath": string;
    "downloadRoot": string;
    "fileListUrl": string;
    "fileListUsername": string;
    "fileListPasskey"?: string;
    "qbittorrentUrl": string;
    "qbittorrentUsername": string;
    "qbittorrentPassword"?: string;
    "downloadEngine": string;
    "torrentPeerPort": number;
    "torrentSessionDir": string;
    "initialBufferBytes": number;
    "readAheadBytes": number;
    "pieceWaitTimeoutSeconds": number;
    "streamStartBytes": number;
    "catalogMaxAgeHours": number;
    "allocationGb": number;
    "reserveGb": number;
    "evictionRules": string[] | null;
    "protectIncomplete": boolean;
    "protectLeased": boolean;
    "protectFavorites": boolean;
    "protectNeverWatched": boolean;
    "preferredSubtitleLanguage": string;
    "fallbackSubtitleLanguage": string;
    "preferredAudioLanguage": string;
    "tmdbApiKey"?: string;
    "metadataLanguage": string;
    "metadataFallbackLanguage": string;
    "artworkCachePath": string;
    "artworkCacheMaxBytes": number;
    "subDLUrl": string;
    "subDLApiKey"?: string;
    "subtitleCachePath": string;
    "subtitleCacheMaxBytes": number;
    "ffprobePath": string;
    "ffmpegPath": string;
    "watchedThresholdPercent": number;
    "maxConcurrentJobs": number;
    "titleRefreshTimeoutMinutes": number;
    "fileListPasskeyConfigured": boolean;
    "qbittorrentPasswordConfigured": boolean;
    "tmdbApiKeyConfigured": boolean;
    "subDLApiKeyConfigured": boolean;
    "settingsPath": string;
}
