// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Settings {
    "instanceName": string;
    "listenAddress": string;
    "trustedCidrs": string[] | null;
    "databasePath": string;
    "downloadRoot": string;
    "fileListUrl": string;
    "fileListUsername": string;
    "fileListPasskey"?: string;
    "qbittorrentUrl": string;
    "qbittorrentUsername": string;
    "qbittorrentPassword"?: string;
    "downloadEngine": string;
    "torrentPeerPort": number;
    "torrentSessionDir": string;
    "initialBufferBytes": number;
    "readAheadBytes": number;
    "pieceWaitTimeoutSeconds": number;
    "streamStartBytes": number;
    "catalogMaxAgeHours": number;
    "allocationGb": number;
    "reserveGb": number;
    "evictionRules": string[] | null;
    "protectIncomplete": boolean;
    "protectLeased": boolean;
    "protectFavorites": boolean;
    "protectNeverWatched": boolean;
    "preferredSubtitleLanguage": string;
    "fallbackSubtitleLanguage": string;
    "preferredAudioLanguage": string;
    "tmdbApiKey"?: string;
    "metadataLanguage": string;
    "metadataFallbackLanguage": string;
    "artworkCachePath": string;
    "artworkCacheMaxBytes": number;
    "subDLUrl": string;
    "subDLApiKey"?: string;
    "subtitleCachePath": string;
    "subtitleCacheMaxBytes": number;
    "ffprobePath": string;
    "ffmpegPath": string;
    "watchedThresholdPercent": number;
    "maxConcurrentJobs": number;
    "titleRefreshTimeoutMinutes": number;
}
