// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Bindings is the Wails service behind the desktop pages: server control,
 * the settings transport, autostart, and data-dir helpers. The runner
 * (Task 6) injects the store and supervisor it shares with the server;
 * wails wraps this struct by reflection at runtime, so it stays plain Go.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as httpapi$0 from "../adapters/httpapi/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../platform/config/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AutostartStatus reads the OS launch-on-boot artifact back; the OS is the
 * source of truth, never memory.
 */
export function AutostartStatus(): $CancellablePromise<boolean> {
 return $Call.ByName("github.com/mihaiflorentin88/torrent-tv/internal/gui.Bindings.AutostartStatus");
}

/**
 * ChangeDataDir relocates the data directory to target: a running server
 * is stopped first and restarted afterwards, datadir.Relocate moves the
 * contents and writes the data.location pointer atomically (a non-empty
 * target is refused; any failure leaves the source untouched), and the
 * settings store swaps to the new location.
 */
export function ChangeDataDir(target: string): $CancellablePromise<void> {
 return $Call.ByName("github.com/mihaiflorentin88/torrent-tv/internal/gui.Bindings.ChangeDataDir", target);
}

/**
 * DataDirInfo returns the resolved data directory and where it came from
 * ("flag", "pointer", or "default").
 */
export function DataDirInfo(): $CancellablePromise<[string, string]> {
 return $Call.ByName("github.com/mihaiflorentin88/torrent-tv/internal/gui.Bindings.DataDirInfo");
}

/**
 * DisableAutostart removes the OS launch-on-boot artifact.
 */
export function DisableAutostart(): $CancellablePromise<void> {
 return $Call.ByName("github.com/mihaiflorentin88/torrent-tv/internal/gui.Bindings.DisableAutostart");
}

/**
 * EnableAutostart registers launch-on-boot: the running executable with
 * --minimized --data-dir <resolved data dir>, so launches never depend on a
 * working directory.
 */
export function EnableAutostart(): $CancellablePromise<void> {
 return $Call.ByName("github.com/mihaiflorentin88/torrent-tv/internal/gui.Bindings.EnableAutostart");
}

/**
 * LoadSettings returns the settings exactly as GET /api/v1/settings serves
 * them: secrets blanked, Configured flags, settings file path.
 */
export function LoadSettings(): $CancellablePromise<httpapi$0.SettingsView> {
 return $Call.ByName("github.com/mihaiflorentin88/torrent-tv/internal/gui.Bindings.LoadSettings");
}

/**
 * MissingRequired lists the required settings still absent; the Settings
 * page banners it and deep-links the Tracker tab.
 */
export function MissingRequired(): $CancellablePromise<string[] | null> {
 return $Call.ByName("github.com/mihaiflorentin88/torrent-tv/internal/gui.Bindings.MissingRequired");
}

/**
 * OpenPath reveals a well-known folder in the OS file manager: kind is
 * "logs" (<data dir>/logs) or "data" (the data dir itself).
 */
export function OpenPath(kind: string): $CancellablePromise<void> {
 return $Call.ByName("github.com/mihaiflorentin88/torrent-tv/internal/gui.Bindings.OpenPath", kind);
}

/**
 * OpenURL opens an http(s) URL in the default browser — the Downloads
 * page's Play hands playback off to the web player this way. The scheme
 * allow-list keeps arbitrary content (file://, custom schemes, command
 * strings) away from the OS opener, and the URL travels as one argv
 * element — never a shell string.
 */
export function OpenURL(url: string): $CancellablePromise<void> {
 return $Call.ByName("github.com/mihaiflorentin88/torrent-tv/internal/gui.Bindings.OpenURL", url);
}

/**
 * OpenWebUI opens the server's web surface in the default browser. The port
 * follows the running (or most recently run) server; the loopback host is
 * fixed: the web UI is this machine's window onto the same server.
 */
export function OpenWebUI(): $CancellablePromise<void> {
 return $Call.ByName("github.com/mihaiflorentin88/torrent-tv/internal/gui.Bindings.OpenWebUI");
}

/**
 * Quit shuts the server down and exits the application. The runner may
 * inject quitFn (the wails app's Quit) to run its own teardown instead.
 */
export function Quit(): $CancellablePromise<void> {
 return $Call.ByName("github.com/mihaiflorentin88/torrent-tv/internal/gui.Bindings.Quit");
}

/**
 * ReadLogs returns the lines appended to the GUI session's server log
 * (<data dir>/logs/server.jsonl, the same file OpenPath("logs") reveals)
 * since the byte offset of the previous call. An offset past the log's
 * size — truncation or rotation — restarts from the beginning. When the
 * unread window exceeds logTailCap the newest logTailCap bytes are
 * returned instead, starting just after the line the cap cuts into, so a
 * viewer that polls rarely stays bounded. Lines are returned raw; JSONL
 * rendering is the client's job. A line still being written is held back
 * until it is complete.
 */
export function ReadLogs(offset: number): $CancellablePromise<$models.LogTail> {
 return $Call.ByName("github.com/mihaiflorentin88/torrent-tv/internal/gui.Bindings.ReadLogs", offset);
}

/**
 * RestartServer applies restart-required settings: Stop then Start.
 */
export function RestartServer(): $CancellablePromise<void> {
 return $Call.ByName("github.com/mihaiflorentin88/torrent-tv/internal/gui.Bindings.RestartServer");
}

/**
 * SaveSettings mirrors the HTTP PUT /api/v1/settings contract: native-path
 * probe, secrets-preserving save, restart-required diff. A save that
 * completes the required settings while the server is stopped auto-starts
 * it (the GUI form of "starts automatically once configuration is set").
 */
export function SaveSettings(next: config$0.Settings): $CancellablePromise<$models.SaveResult> {
 return $Call.ByName("github.com/mihaiflorentin88/torrent-tv/internal/gui.Bindings.SaveSettings", next);
}

/**
 * ServerState reports the current lifecycle state for page mounts that miss
 * the last 'server:state' event.
 */
export function ServerState(): $CancellablePromise<$models.StateEvent> {
 return $Call.ByName("github.com/mihaiflorentin88/torrent-tv/internal/gui.Bindings.ServerState");
}

/**
 * SettingsSchema returns the settings schema, identical to the HTTP
 * /api/v1/settings/schema items.
 */
export function SettingsSchema(): $CancellablePromise<httpapi$0.SchemaField[] | null> {
 return $Call.ByName("github.com/mihaiflorentin88/torrent-tv/internal/gui.Bindings.SettingsSchema");
}

/**
 * StartServer brings the server up (refused while required settings are
 * missing; that shows setup, not failure).
 */
export function StartServer(): $CancellablePromise<void> {
 return $Call.ByName("github.com/mihaiflorentin88/torrent-tv/internal/gui.Bindings.StartServer");
}

/**
 * StopServer gracefully shuts the running server down.
 */
export function StopServer(): $CancellablePromise<void> {
 return $Call.ByName("github.com/mihaiflorentin88/torrent-tv/internal/gui.Bindings.StopServer");
}

/**
 * Version reports the server version (composition.Version, ldflags-injected
 * in release builds).
 */
export function Version(): $CancellablePromise<string> {
 return $Call.ByName("github.com/mihaiflorentin88/torrent-tv/internal/gui.Bindings.Version");
}
