// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SaveResult is the SaveSettings response: whether the settings persisted,
 * whether any restart-required field changed, and whether the save completed
 * setup and auto-started the server.
 */
export interface SaveResult {
 "saved": boolean;
 "restartRequired": boolean;
 "autoStarted": boolean;
}

/**
 * State is the server lifecycle phase the GUI renders in its status
 * pill, tray, and buttons.
 */
export enum State {
 /**
  * The Go zero value for the underlying type of the enum.
  */
 $zero = "",

 StateStopped = "stopped",
 StateStarting = "starting",
 StateRunning = "running",
 StateStopping = "stopping",
 StateFailed = "failed",
};

/**
 * LogTail is one ReadLogs page: the raw lines read from the GUI session's
 * server log, the byte offset the next call must pass, and the log's
 * current size.
 */
export interface LogTail {
 "lines": string[];
 "nextOffset": number;
 "size": number;
}

/**
 * StateEvent is the server lifecycle payload the Wails runner emits on the
 * 'server:state' topic and the ServerState binding returns. The TS mirror is
 * desktop/src/lib/state.ts.
 */
export interface StateEvent {
 "state": State;
 "error"?: string;
 "address"?: string;
}
